export const projects = [
  {
    id: "1",
    screenshot: "/aroe-page2.png",
    title: "Aroê",
    subTitle: "Plataforma para medicamentos manipulados",
    stack: ["Figma", "Design Thinking", "UX Research"],
    description:
      "Aroê é uma plataforma que simplifica o acesso a medicamentos manipulados, oferecendo uma experiência digital intuitiva e eficiente para pacientes e para farmácias.",
    date: "2026",
    github: "https://github.com/Equipe-Aroe",
    live: "https://aroe-app.vercel.app",
    color: "rgba(168,85,247,0.7)",
    btnBg: "rgba(168,85,247,0.2)",
    btnBgHover: "rgba(139,92,246,0.85)",
    cardBg: "rgba(168,85,247,0.08)",
  },
  {
    id: "2",
    screenshot: "/conecta-atleta.png",
    title: "Conecta Atleta",
    subTitle: "Rede para atletas, patrocinadores e organizadores",
    stack: [
      "Next.js",
      "TypeScript",
      "Prisma",
      "PostgreSQL",
      "Tailwind",
      "React",
    ],
    description:
      "Conecta Atleta é uma plataforma para conectar atletas, patrocinadores e organizadores esportivos em uma experiência digital colaborativa.",
    date: "2025",
    github: "",
    live: "https://conecta-atleta-seven.vercel.app/",
    color: "rgba(59,130,246,0.85)",
    btnBg: "rgba(59,130,246,0.16)",
    btnBgHover: "rgba(30,64,175,0.85)",
    cardBg: "rgba(59,130,246,0.08)",
  },
  {
    id: "3",
    screenshot: "/joe-barra-limpa.png",
    title: "Joe Barra Limpa",
    subTitle: "Catálogo digital para limpeza de barras de direção",
    stack: ["Next.js", "React", "Tailwind"],
    description:
      "Website institucional e catálogo digital para empresa especializada em limpeza de barras de direção de caminhões.",
    date: "2025",
    github: "",
    live: "https://joe-barra-limpa.vercel.app",
    color: "rgba(234,179,8,0.85)",
    btnBg: "rgba(234,179,8,0.16)",
    btnBgHover: "rgba(161,98,7,0.85)",
    cardBg: "rgba(234,179,8,0.08)",
  },
  {
    id: "4",
    screenshot: "/instagram-clone.png",
    title: "Instagram Clone",
    subTitle: "Clone responsivo da interface do Instagram",
    stack: ["React", "Vite", "CSS"],
    description:
      "Clone responsivo da interface do Instagram construído com React e foco em layout, interações e usabilidade.",
    date: "2025",
    github: "https://github.com/Amanda-SCarvalho/instagramClone",
    live: "https://instagram-clone-five-cyan.vercel.app/",
    color: "rgba(147,51,234,0.85)",
    btnBg: "rgba(147,51,234,0.16)",
    btnBgHover: "rgba(88,28,135,0.85)",
    cardBg: "rgba(147,51,234,0.08)",
  },
];
