export const projects = [
  {
    id: '1',
    screenshot: '/conecta-atleta.png',
    title: 'Conecta Atleta',
    subTitle: 'Plataforma de conexão entre atletas e patrocinadores',
    stack: [
      'next.js',
      'react',
      'typescript',
      'tailwindcss',
      'shadcn/ui',
      'prisma',
      'postgresql',
      'neon',
      'nextauth',
      'zod',
      'react query',
    ],
    description: `Conecta Atleta é uma plataforma fullstack desenvolvida para conectar atletas, patrocinadores e fãs...`,
    date: 'Mar 10, 2025',
    github: '',
    live: '',
    color: 'rgba(59,130,246)', // azul
    btnBg: 'rgba(30,64,175,0.5)',
    btnBgHover: 'rgba(15,23,42)',
    cardBg: 'rgba(59,130,246,0.08)',
  },

  {
    id: '2',
    screenshot: '/instagram-clone.png',
    title: 'Instagram Clone',
    subTitle: 'Rede social com feed, interações e perfis',
    stack: [
      'react',
      'typescript',
      'tailwindcss',
      'firebase',
      'context api',
    ],
    description: `Clone do Instagram desenvolvido com foco em replicar a experiência de uma rede social moderna...`,
    date: 'Jan 15, 2025',
    github: '',
    live: '',
    color: 'rgba(147,51,234)', // roxo
    btnBg: 'rgba(88,28,135,0.5)',
    btnBgHover: 'rgba(59,7,100)',
    cardBg: 'rgba(147,51,234,0.08)',
  },

  {
    id: '3',
    screenshot: '/joe-barra-limpa.png',
    title: 'Joe Barra Limpa',
    subTitle: 'Site institucional para elétrica automotiva',
    stack: [
      'next.js',
      'react',
      'typescript',
      'tailwindcss',
      'css variables',
    ],
    description: `Site institucional desenvolvido para uma empresa especializada em elétrica automotiva...`,
    date: 'Feb 5, 2025',
    github: '',
    live: '',
    color: 'rgba(234,179,8)', // amarelo
    btnBg: 'rgba(161,98,7,0.5)',
    btnBgHover: 'rgba(120,53,15)',
    cardBg: 'rgba(234,179,8,0.08)',
  },
];